#!/usr/bin/env bash
# installs nginx on a server

apt-get -y update
apt-get -y install nginx
mkdir --parents /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart